### ISSUE TITLE
Not detecting total screen size correctly with multiple monitors

### ISSUE THREAD

**Issue by eater** [phillipberndt/autorandr#116]
I have a laptop (with its display off) connected to two external monitors, one landscape and one portrait. In this configuration, xrandr reports 
` Screen 0: minimum 320 x 200, current 2970 x 1680, maximum 8192 x 8192`

When I save that as an autorandr profile, then restore it, one of the screens is cut off: 
` Screen 0: minimum 320 x 200, current 3600 x 1080, maximum 8192 x 8192`

I have to manually add `fb 2970x1680` to the autorandr config file for that profile.

**Comment by adbrucker** [comment]
Hi,
I observed the same or an similar issue. Since a couple of weeks (most likely an update of the Intel X11 drivers), the fb size calculated by `get_fb_dimension()` is wrong - at least if one monitor is left/right rotated. 

Disabling the manual configuration of the fb sizes fixes the issue for me. Not sure if the manual fb size computation in `autorandr` is still required or might be removed completely due to improvements of `xrandr` et al ... 

I am currently looking closer into this issue and will do some further tests during the next couple of days. 

Best,
Achim

**Comment by adbrucker** [comment]
I am using since a month a patched version of autorandr where there call to get_fb_dimension() is disabled, i.e., I just removed lines 690-696. It "works for me" - but as the change is trivial and I do not know for which configurations the dimension computation is required, I hesitated to do a pull request that just removed get_fb_dimension(). 

Cheers,
Achim

**Comment by phillipberndt** [comment]
Hey, sorry for the severely delayed reaction. @Mange the issue you're seeing is related to what I wrote in #33, autorandr doesn't currently handle global (non-output related) options in config files correctly, and also unconditionally adds `--fb` even if it's in the `config` file.

**Comment by phillipberndt** [comment]
@eater @Mange @adbrucker  Could you please test whether #117 fixes the issue for you?

**Comment by Mange** [comment]
#117 works for my setup!

(1 screen horizontal, 1 screen vertical next to it)
