### ISSUE TITLE
Old setting name in systemd service file

### ISSUE THREAD

**Issue by frangio** [phillipberndt/autorandr#69]
The `StartLimitInterval` setting [was renamed](https://github.com/systemd/systemd/commit/f0367da7d1a61ad698a55d17b5c28ddce0dc265a) to `StartLimitIntervalSec` in systemd-230.

**Comment by phillipberndt** [comment]
Thanks. Do you know when `StartLimitInterval` is scheduled to be completely removed?

(At least Ubuntu stable does still use a version where the option is named `StartLimitInterval`, and putting both versions into the unit file triggers a warning for old versions of systemd, and will trigger one for versions where `StartLimitInterval` has been removed as well.. so renaming this once every distribution's stable release uses a version where the rename has taken place seems to be the only viable option at first glance.)

**Comment by frangio** [comment]
Well until a few months ago they had no plans for removal, according to [a comment](https://github.com/systemd/systemd/pull/3148#issuecomment-215688057) by @poettering.

I agree it's best to not rename it in autorandr yet.

**Comment by Flowdalic** [comment]
At least in gentoo and debian the stable version of sytemd is >= 230, so I guess it's a good time to rename the setting.

**Comment by phillipberndt** [comment]
[Ubuntu LTS](https://packages.ubuntu.com/xenial/systemd) still uses 229. This isn't much of a problem on its own, I believe most users of advanced packages such as this one will use the latest release, but several forks of Ubuntu are based on the LTS releases, most notably, Mint. The next LTS release is schedules for April 2018. We should wait until then.

(Am I assuming right that you want this for cosmetic reasons, not because Lennart changed his mind and systemd dropped support for the old syntax in the meantime?)

**Comment by RasmusWL** [comment]
Just FYI, I'm on Ubuntu LTS. I'm not always happy about it, and have been contemplating going to arch, but haven't done it. So I'm happy that you'll wait for a new LTS :+1:
