### ISSUE TITLE
What license does this software use?

### ISSUE THREAD

**Issue by jamesan** [phillipberndt/autorandr#7]
I'm assuming everything in this repository is open source/copy-left like GPLv2 or GPLv3, but it doesn't seem to indicate explicitly. Neither this repo, nor its predecessor, https://github.com/wertarbyte/autorandr, nor any references to autorandr or autodisper return any clues.

I'm updating Arch Linux's user contributed AUR package for autorandr and noticed its license field is blank. This would greatly help in my housekeeping of that package build. Thanks!

**Comment by tachylatus** [comment]
I second bingmann's opinion :-)

**Comment by phillipberndt** [comment]
Let's go with the GPL then. I already reworked the fingerprinting, but after doing some research on the topic I believe that we need to have all authors' consent. Further contributors were @ChrisDunder, @maciex, @stormc, @mrj10 and @formorer. Another scripts within this repository was written by @QueezyTheGreat.

Do you consent with publishing your contributions to autorandr under the terms of the GPL 3?

**Comment by formorer** [comment]
On Fri, 02 Jan 2015, Phillip Berndt wrote:

> Let's go with the GPL then. I already reworked the fingerprinting, but after doing some research on the topic I believe that we need to have all authors' consent. Further contributors were @ChrisDunder, @maciex, @stormc, @mrj10 and @formorer. Another scripts within this repository was written by @QueezyTheGreat.
> 
> Do you consent with publishing your contributions to autorandr under the terms of the GPL 3?
I would prefer MIT, but GPL is also fine.

Alex

**Comment by queezythegreat** [comment]
Hi, I think both MIT and GPL are fine, I have no objections. I also like the [MPL License 2.0](http://en.wikipedia.org/wiki/Mozilla_Public_License).

**Comment by stormc** [comment]
I'm fine with any license you find appropriate

**Comment by maciex** [comment]
I think GPL is fine.

**Comment by phillipberndt** [comment]
In bug #7, tachylatus suggested to rework the storage/application of configurations to account for pluggable graphics cards. My comment there might also be relevant to this issue:

> Since this is a major change, let's wait a few days with this: Regarding the licensing issue #7, I noticed that much of wertarbyte's code is too trivial to be rewritten in another way, and I don't know enough about copyright law to be absolutely certain that this is not a problem. I wrote him an email yesterday, and hopefully he'll reply. If he doesn't, this conceptual change would be a great opportunity to rewrite the whole thing from scratch, keeping configuration/parameter compatibility of course. (autorandr isn't that big/complicated, after all.. and we could switch to Python or Perl to ditch the awk/sed scripts.)

The background is that in the meantime, I've read that such trivial code lines could still be a problem (there is an example with a copyrighted `/bin/true` on google). That what we work with here is a fork of wertarbyte's code obviously doesn't make that simpler. I don't believe that autorandr will ever be the object of a lawsuit, or that wertarbyte will sue anyone about it, but I also don't want to be the one to take the chance that I'm wrong. So if wertarbyte does not reply, we'll have multiple choices:

* Someone of you forks my [`license` branch](https://github.com/phillipberndt/autorandr/tree/license), optionally reverts bbe8f8b547256542ad332bfee1614cf7137f9e5d, and adds a copyright notice at the top. We'll all work with that code base, from then on.
* We switch to a true rewrite. This could either be another bash script (in which case we could reuse much, do a `git blame` on autorandr in the license branch), or be in another language, as written above. [Here's a quick showcase of how this could be done in Python](https://github.com/phillipberndt/autorandr/blob/license/autorandr.py). The script should be fully (except the configuration file) compatible with autorandr by now (and it additionally supports transformation matrices, gamma levels, refresh rates & reflections), but still
<blockquote>This is very early and experimental code, and I haven't tested it very much. [..] Please consider this as a suggestion on where we could go with autorandr rather than something I'd like to impose on anyone.. I'm open to suggestions.</blockquote>
tachylatus started [a perl version](https://github.com/tachylatus/autorandr/blob/perl-experiment/autorandr.pl), if you'd prefer that. Or, if you'd prefer the rewrite option and to stick with bash, go ahead and do that.

I'm fine with any of these.

**Comment by ChrisDunder** [comment]
I prefer GPL.

~ cd

**Comment by phillipberndt** [comment]
wertarbyte just commented in https://github.com/wertarbyte/autorandr/issues/24

> After a while, I finally got around to this - licence should be GPLv3, so feel free to package :-)

Which means that autorandr is now officially GPLv3. For now, I've reverted the commit that removed parts of his code from the `license` branch and merged the branch into master. I'll still have to decide on how to move forward with the Python version. I will definitively maintain both for some time, but whether I do this in a single branch, two branches, repositories, under which name, etc. is all open. If you're interested in the future of both versions (e.g. if you maintain a package for this fork), subscribe to #12 for updates on that.
