### ISSUE TITLE
TODO: Rework disabled output handling (DisplayPort MST, hot-plug graphics)

### ISSUE THREAD

**Issue by tachylatus** [phillipberndt/autorandr#8]
Since the introduction of DisplayPort MST and hot-pluggable graphics cards, we can no longer assume the list of outputs is stable.
We need to implement a different logic for disabled outputs:
- autorandr config should only contain enabled outputs
- on config load, all other outputs should be disabled

**Comment by phillipberndt** [comment]
Sounds reasonable.

Since this is a major change, let's wait a few days with this: Regarding the licensing issue #7, I noticed that much of wertarbyte's code is too trivial to be rewritten in another way, and I don't know enough about copyright law to be absolutely certain that this is not a problem. I wrote him an email yesterday, and hopefully he'll reply. If he doesn't, this conceptual change would be a great opportunity to rewrite the whole thing from scratch, keeping configuration/parameter compatibility of course. (autorandr isn't that big/complicated, after all.. and we could switch to Python or Perl to ditch the awk/sed scripts.)

**Comment by tachylatus** [comment]
Yeah, I guess it would make sense to just rewrite it, although I don't have much experience with neither Python nor Perl ;-)

I was planning on working on these new issues/requests myself (see #9).

**Comment by phillipberndt** [comment]
I couldn't resist: https://github.com/phillipberndt/autorandr/blob/license/autorandr.py

This is very early and experimental code, and I haven't tested it very much. Both your suggestions should already work though. Please consider this as a suggestion on where we *could* go with autorandr rather than something I'd like to impose on anyone.. I'm open to suggestions.

(I'll write a follow-up to #7 tomorrow, where I'll also ask the others that don't follow this issue for their opinion & more on why I think a rewrite is the safest option.)

**Comment by tachylatus** [comment]
Haha, that's brilliant!
- I couldn't resist either, and have been learning Perl since yesterday.

Here's my little Perl experiment:
https://github.com/tachylatus/autorandr/blob/perl-experiment/autorandr.pl

I only just got the xrandr output parsing working (including transform matrix and reflections), but the whole program is far from done.
Anyway, your Python version looks much nicer, so I guess I'll start learning some Python now :-)

**Comment by phillipberndt** [comment]
See #7; a bash implementation of this might be of interest, after all. (Depends on which version you'll be going to use. ;-))

**Comment by phillipberndt** [comment]
Does this work as expected for you in the Python version? It should, but I still haven't thoroughly tested this.

**Comment by phillipberndt** [comment]
I have been using this for some time now and it seems to be stable. This night need some changes to properly support providers when RandR 1.5 becomes more widespread, still, for now, I'll close this as fixed.
