### ISSUE TITLE
handle compositor before and after change of setup to prevent xautolock from failing

### ISSUE THREAD

**Issue by dvzrv** [phillipberndt/autorandr#93]
I'm currently in a setup in which:

- I don't use a desktop manager (DM)
- start X with startx
- use compton as compositor with minimal configuration (`compton -d "$DISPLAY" -CGb &`), started in .xprofile
- use xautolock to automatically lock and disable screens after a while
- use autorandr to switch between certain multi-monitor configurations

However, in this configuration, as long as compton is active, after a switch of configuration with autorandr, xautolock goes to defunct, requiring me to kill the session and logging back in (if I want automatic locking and disabling of screens, which I obviously want ;-) ).
If I don't use compton, all seems fine during switching.

If I understand correctly from autorandr's help output, it is possible to use a **block** script _before_ and a **postswitch** script _after_ the switch.
Will this enable me to kill and start compton as a background task respectively?
Can these be shell scripts or do they have to be python based? This is not clearly stated in the output.

btw: The issue does not occur, when using something like arandr to switch screen setups! So this must have something to with the way autorandr activates/deactivates screens or the time it uses for it.

**Comment by phillipberndt** [comment]
> If I understand correctly from autorandr's help output, it is possible to use a block script before and a postswitch script after the switch.

The `block` script can be used to prevent automated loading of a certain profile. It is run for every (!) profile when you run `autorandr` without specifying a specific profile. The `preswitch` script is probably better suited to your use case.

>  Will this enable me to kill and start compton as a background task respectively?

Yes. (Wouldn't it be easier to restart xautolock?)

>  Can these be shell scripts or do they have to be python based? This is not clearly stated in the output.

The files can be arbitrary executables, including shell scripts. (..make sure to have the +x bit set.)

> btw: The issue does not occur, when using something like arandr to switch screen setups! So this must have something to with the way autorandr activates/deactivates screens or the time it uses for it.

autorandr disables screens first, then enables them in a specific order. This is because many drivers have some issues when there's too many changes to the configuration at once. Maybe that's the source of the problem? You could check whether the changes from #88 (and use of the new command line flag) fix things for you - they allow to perform every change in a single `xrandr` call.

**Comment by dvzrv** [comment]
Thanks for the answers!

I just tested with 1.3 (and build a [package](https://aur.archlinux.org/packages/autorandr/) for it) and the issue seems to be gone, afaics.
No need to even use the post-/pre-scripts.

I think before I had the [autorandr-git package](https://aur.archlinux.org/packages/autorandr-git/) installed, which seems to be stuck some commits after the 1.0 release.

Glad to see there's development ongoing and with releases! Maybe we can even push this to [community] in the forseeable future.
